#!/bin/bash
set -e

# Liste der Fallzahlen pro Gemeinde

FILE=$1
[[ -s $FILE ]] || exit 0

TEXT=$(pup div.magazinetext ul li text{} < $1)
[[ "$TEXT" =~ 'Flecken Adelebsen' ]] || exit 0

export ID=$(echo "$FILE" | tr -cd 0-9)

# skip duplicated article
[[ $ID -eq "3307" ]] && exit

export DATES=$(pup .artikeldatum text{} < $FILE | xargs | perl -ne '
  s/(\d\d)\.(\d\d)\.(20\d\d)/$3-$2-$1/g;               # convert to YYYY-MM-DD
  print join ",", (($_ =~ /([0-9-]+)/g), "")[0,1];     # created, modified
')

echo "$TEXT" | perl -CS -nE '
  my ($ort, $zahlen) = $_ =~ m/^([GSF].+?)([0-9.(\/\s]+)[)\s]*$/;
  exit unless $ort;
  $ort =~ s/ zusammen//;
  $zahlen =~ s/[\s().]//g;
  say join ",", $ENV{DATES}, $ort, ((split("/", $zahlen), "")[0,1]), $ENV{ID};
' | tac | sort -u -t, -k3,3
